### ISSUE TITLE
deploy a copy of the sso dashboard to Kubernetes

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-itcloud/iam-project#16]

**Comment by danielhartnell** [comment]
This will be an interesting step forward in our work. Everything that we've done so far should come together to enable this.

In two weeks, we would like to have a copy of the SSO dashboard running in our Kubernetes cluster and capable of handling some small percentage of our production traffic. I expect this to help highlight issues and gaps in the work that I've done so far.

After reviewing the dashboard application, the work required to accomplish this will actually be fairly minimal. We should not keep things like DynamoDB or IAM policies in sync between two separate accounts so we will simply use IAM to bridge the gap. This wouldn't be great in the long run but it will work just fine for our proof of concept.

Here's what we need:

- Create the Kubernetes YAML for a deployment and a service for the SSO dashboard Flask application. I need to get confirmation but I believe this pod may also include Redis
- Create a new IAM role that the pod can assume through kube2iam and annotate the deployment to specify that
- This role should be trusted by a new IAM role in the current production site's AWS account
- That new role should have the existing SSO dashboard policies attached to provide access to resources like DynamoDB
- Validate that Kubernetes can pull the container image from ECR
- Quickly document the process to manually update the deployment when a new container image is built
- Validate that the pod is functioning and add some basic monitoring to ensure that the pod / cluster is not falling over when it receives some traffic
- Perform the same work for development
- Update the Route 53 configuration to do weighted routing to the development environment

**Comment by danielhartnell** [comment]
I am currently working to test the IAM configuration. I'll work with Andrew before making changes to the current production account (adding new roles or a trusted entity).

**Comment by danielhartnell** [comment]
Notes on IAM configuration:

Within the EKS cluster account, I created a new IAM role called "eks-sso-dashboard-prod" (noted so I don't lose track of it). This has a trust relationship to the "terraform-eks-development-node" role which should be what is assigned to kube2iam and is what the Kubernetes worker nodes are assigned.

For testing, I just assigned a policy to "eks-sso-dashboard-prod" which provides S3 read access.

I have a debug shell with a pod annotation specifying the role I want the pod to assume:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: debug-shell
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: "arn:aws:iam::${ACCOUNT_ID}:role/eks-sso-dashboard-prod"
      labels:
        app: debug-shell
    spec:
      containers:
      - name: debug-shell
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "while true; do echo debug mode; sleep 3600; done"]
```

Testing shows that this works. The pod is limited to S3 read access.

**Comment by danielhartnell** [comment]
Moving forward, we will need to create a new role in the target AWS account with a trust relationship to the "eks-sso-dashboard-prod" role and attach the policies needed to allow the SSO dashboard application to work.

After that, we'll need to modify the dashboard application in some way to make sure it tries to access the resources in the target account rather than the account where the app is running in Kubernetes. I'll probably need Andrew's help tracking down those changes.

If I'm not overlooking anything important, this should be all we need to get the app up and running. We will also need to adjust the IAM configuration to allow Kubernetes to pull the container image from the ECR repository in the target account.

**Comment by danielhartnell** [comment]
Something like this should be sufficient for testing the deployment. We can discuss the ingress controller (if needed) and service configuration:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sso-dashboard-deployment
  labels:
    app: sso-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-dashboard
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: "arn:aws:iam::${ACCOUNT_ID}:role/eks-sso-dashboard-prod"
      labels:
        app: sso-dashboard
    spec:
      containers:
        - name: sso-dashboard
          image: ${ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/sso-dashboard-latest
          ports:
            - containerPort: 5000
```
